package id.ac.poliban.mi.auzan.customlistview;

import java.util.ArrayList;
import java.util.List;

public class CountryData {
   static List<Country>getAllCoutries(){
       List<Country> data = new ArrayList<>();
       data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/125px-Flag_of_Indonesia.svg.png","Indonesia","Republik Indonesia (RI) atau Negara Kesatuan Republik Indonesia (NKRI), atau lebih umum disebut Indonesia, adalah negara di Asia Tenggara yang dilintasi garis khatulistiwa dan berada di antara daratan benua Asia dan Australia, serta antara Samudra Pasifik dan Samudra Hindia. Indonesia adalah negara kepulauan terbesar di dunia yang terdiri dari 17.504 pulau.[11] Nama alternatif yang biasa dipakai adalah Nusantara.[12] Dengan populasi Hampir 270.054.853 jiwa pada tahun 2018,[13] Indonesia adalah negara berpenduduk terbesar keempat di dunia dan negara yang berpenduduk Muslim terbesar di dunia, dengan lebih dari 230 juta jiwa.[14][15] "));
       data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/125px-Flag_of_the_United_States.svg.png","Amerika Serikat", "Amerika Serikat, disingkat dengan AS (bahasa Inggris: United States of America/U.S.A. disingkat United States/US), atau secara umum dikenal dengan Amerika saja,[catatan 1] adalah sebuah negara republik konstitusional federal yang terdiri dari lima puluh negara bagian dan sebuah distrik federal.[7] Negara ini terletak di bagian tengah Amerika Utara, yang menjadi lokasi dari empat puluh delapan negara bagian yang saling bersebelahan, beserta distrik ibu kota Washington, D.C.. Amerika Serikat diapit oleh Samudra Pasifik dan Atlantik di sebelah barat dan timur, berbatasan dengan Kanada di sebelah utara, dan Meksiko di sebelah selatan. Dua negara bagian lainnya, yaitu Alaska dan Hawaii, terletak terpisah dari dataran utama Amerika Serikat. Negara bagian Alaska terletak di sebelah ujung barat laut Amerika Utara, berbatasan dengan Kanada di sebelah timur dan Rusia di sebelah barat, yang dipisahkan oleh Selat Bering. Sedangkan negara bagian Hawaii adalah sebuah kepulauan yang berlokasi di Samudra Pasifik. Amerika Serikat juga memiliki beberapa teritori di Pasifik dan Karibia. Dengan luas wilayah 3,79  juta mil persegi (9,83 juta km2) dan jumlah penduduk sebanyak 315 juta jiwa, Amerika Serikat merupakan negara terluas ketiga atau keempat di dunia, dan terbesar ketiga menurut jumlah penduduk. Amerika Serikat adalah salah satu negara multietnik dan multikultural di dunia. Hal tersebut muncul akibat adanya imigrasi besar-besaran dari berbagai penjuru dunia.[8] Iklim dan geografi Amerika Serikat juga sangat beragam dan negara ini menjadi tempat tinggal bagi beragam spesies. "));
       data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/125px-Flag_of_Japan.svg.png", "Jepang", "Jepang (Jepang: 日本 Nippon atau Nihon; nama resmi: 日本国 Tentang suara ini Nipponkoku atau Nihonkoku, nama harfiah: \"Negara Jepang\") adalah sebuah negara kepulauan di Asia Timur. Letaknya di ujung barat Samudra Pasifik, di sebelah timur Laut Jepang, dan bertetangga dengan Republik Rakyat Tiongkok, Korea, dan Rusia. Pulau-pulau paling utara berada di Laut Okhotsk, dan wilayah paling selatan berupa kelompok pulau-pulau kecil di Laut Tiongkok Timur, tepatnya di sebelah selatan Okinawa yang bertetangga dengan Taiwan. "));
       data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Russia.svg/125px-Flag_of_Russia.svg.png", "Rusia", "Federasi Rusia[12] (Rusia: Росси́йская Федера́ция, tr. Rossiyskaya Federatsiya; IPA: [rɐˈsʲijskəjə fʲɪdʲɪˈratsɨjə] ( simak)), umumnya disebut Rusia (Rusia: Росси́я, tr. Rossija; IPA: [rɐˈsʲijə] ( simak)), adalah sebuah negara berdaulat yang membentang dengan luas di sebelah timur Eropa dan utara Asia. Dengan wilayah seluas 17.125.200 km²,[13] Rusia adalah negara terluas di dunia. Wilayahnya mencakup seperdelapan luas daratan bumi,[14][15][16], penduduknya menduduki peringkat kesembilan terbanyak di dunia dengan jumlah sekitar 146 juta jiwa (Maret 2016).[17][18] Wilayahnya membentang sepanjang Asia Utara dan sebagian Eropa timur, Rusia memiliki 11 zona waktu dan wilayahnya terdiri dari berbagai tipe lingkungan dan tanah. Dari barat laut sampai ke tenggara, Rusia berbatasan dengan Norwegia, Finlandia, Estonia, Latvia, Lituania dan Polandia (keduanya berbatasan dengan Kaliningrad Oblast), Belarusia, Ukraina, Georgia, Azerbaijan, Kazakhstan, China, Mongolia, dan Korea Utara. Negara ini berbatasan laut dengan Jepang di Laut Okhotsk dan negara bagian Alaska, Amerika Serikat di Selat Bering. "));
       return data;
   }
}
